'''
Created on Nov 10, 2013

@author: samith
'''

NEGATIVE = 0
POSITIVE = 1
HARD_TO_CLASSIFY = 2
DECISION_LIST = []
DECISION_LIST.insert(NEGATIVE,"NEGATIVE")
DECISION_LIST.insert(POSITIVE,"POSITIVE")
DECISION_LIST.insert(HARD_TO_CLASSIFY,"HARD_TO_CLASSIFY")

SUBJECTIVE = 0
OBJECTIVE = 1